name: Mitigasi Artifact Signing

on:
  push:
    branches: [ main ]

jobs:
  sign-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Merakit aplikasi (simulasi)
      - name: 1. Build Aplikasi Asli
        run: |
          echo "Ini adalah rilis resmi dan aman dari Kelompok 4 Vinix7." > aplikasi-resmi.txt

      # 2. Memasang alat penyegel (Cosign)
      - name: 2. Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      # 3. Membuat sepasang kunci (Private & Public)
      - name: 3. Buat Kunci Kriptografi (Key-Pair)
        run: |
          echo "[*] Menghasilkan gembok dan kunci..."
          env COSIGN_PASSWORD=rahasia_vinix cosign generate-key-pair
          
      # 4. Menstempel aplikasi dengan kunci privat (PENAMBAHAN COSIGN_YES=true)
      - name: 4. Tanda Tangani Artifact (Signing)
        run: |
          echo "[*] Menyegel aplikasi dengan Cosign..."
          env COSIGN_PASSWORD=rahasia_vinix COSIGN_YES=true cosign sign-blob --tlog-upload=false --key cosign.key aplikasi-resmi.txt > aplikasi-resmi.sig
          echo "[+] File .sig berhasil dibuat!"

      # 5. Simulasi Pengecekan (Sistem membuktikan file aman)
      - name: 5. Verifikasi Segel Digital
        run: |
          echo "[*] Mengecek keaslian aplikasi..."
          cosign verify-blob --key cosign.pub --signature aplikasi-resmi.sig aplikasi-resmi.txt
          echo "[+] VERIFIKASI BERHASIL! File asli belum dimanipulasi oleh pihak ketiga."

      # 6. Menyimpan hasil agar bisa diunduh
      - name: 6. Upload Hasil Tersertifikasi
        uses: actions/upload-artifact@v4
        with:
          name: rilis-tersertifikasi
          path: |
            aplikasi-resmi.txt
            aplikasi-resmi.sig
            cosign.pub
